import { Opportunity } from '../types';

export async function fetchDevpostHackathons(): Promise<Opportunity[]> {
  return FALLBACK_HACKATHONS;
}

const FALLBACK_HACKATHONS: Opportunity[] = [
  {
    id: 6001,
    title: 'هاكاثون LEAP 2025',
    type: 'hackathon',
    organization: 'LEAP Conference',
    description: 'أكبر هاكاثون تقني في المملكة العربية السعودية ضمن مؤتمر LEAP.',
    deadline: '2025-09-01',
    location: 'الرياض، المملكة العربية السعودية',
    latitude: 24.7136,
    longitude: 46.6753,
    xpReward: 100,
    registrationLink: 'https://www.leapconference.com',
    imageUrl: null,
    isActive: 1,
    createdAt: new Date().toISOString(),
    status: 'upcoming',
    prize: '50,000 ريال',
  },
  {
    id: 6002,
    title: 'هاكاثون وزارة الاتصالات',
    type: 'hackathon',
    organization: 'وزارة الاتصالات وتقنية المعلومات',
    description: 'هاكاثون لتطوير حلول رقمية مبتكرة لخدمات الحكومة السعودية.',
    deadline: '2025-10-15',
    location: 'جدة، المملكة العربية السعودية',
    latitude: 21.4858,
    longitude: 39.1925,
    xpReward: 80,
    registrationLink: 'https://www.mcit.gov.sa',
    imageUrl: null,
    isActive: 1,
    createdAt: new Date().toISOString(),
    status: 'upcoming',
    prize: '30,000 ريال',
  },
  {
    id: 6003,
    title: 'NASA Space Apps Challenge',
    type: 'hackathon',
    organization: 'NASA',
    description: 'هاكاثون عالمي لحل تحديات الفضاء باستخدام التكنولوجيا والبرمجة.',
    deadline: '2025-10-05',
    location: 'Online + الرياض',
    latitude: null,
    longitude: null,
    xpReward: 120,
    registrationLink: 'https://www.spaceappschallenge.org',
    imageUrl: null,
    isActive: 1,
    createdAt: new Date().toISOString(),
    status: 'upcoming',
    prize: 'جوائز عالمية',
  },
  {
    id: 6004,
    title: 'KAUST Hackathon 2025',
    type: 'hackathon',
    organization: 'جامعة الملك عبدالله للعلوم والتقنية',
    description: 'هاكاثون علمي وتقني لطلاب الجامعات السعودية في مجالات الطاقة والبيئة.',
    deadline: '2025-11-01',
    location: 'ثول، المملكة العربية السعودية',
    latitude: 22.3067,
    longitude: 39.1025,
    xpReward: 90,
    registrationLink: 'https://www.kaust.edu.sa',
    imageUrl: null,
    isActive: 1,
    createdAt: new Date().toISOString(),
    status: 'upcoming',
    prize: '20,000 ريال',
  },
];
