import { Opportunity } from '../types';

export async function fetchRemotiveJobs(): Promise<Opportunity[]> {
  return FALLBACK_INTERNSHIPS;
}

const FALLBACK_INTERNSHIPS: Opportunity[] = [
  {
    id: 5001,
    title: 'مطور تطبيقات موبايل - تدريب',
    type: 'internship',
    organization: 'STC',
    description: 'فرصة تدريبية في تطوير تطبيقات الجوال لطلاب علوم الحاسب والهندسة.',
    deadline: '2025-08-01',
    location: 'الرياض، المملكة العربية السعودية',
    latitude: 24.7136,
    longitude: 46.6753,
    xpReward: 60,
    registrationLink: 'https://jadarat.hrsd.gov.sa',
    imageUrl: null,
    isActive: 1,
    createdAt: new Date().toISOString(),
    status: 'open',
    duration: '3 أشهر',
    salary: '3000 ريال/شهر',
  },
  {
    id: 5002,
    title: 'مهندس برمجيات - تدريب صيفي',
    type: 'internship',
    organization: 'Aramco Digital',
    description: 'برنامج التدريب الصيفي لطلاب الجامعات في مجال البرمجيات وتطوير الأنظمة.',
    deadline: '2025-07-15',
    location: 'الدمام، المملكة العربية السعودية',
    latitude: 26.4207,
    longitude: 50.0888,
    xpReward: 60,
    registrationLink: 'https://jadarat.hrsd.gov.sa',
    imageUrl: null,
    isActive: 1,
    createdAt: new Date().toISOString(),
    status: 'open',
    duration: '2 أشهر',
    salary: '4000 ريال/شهر',
  },
  {
    id: 5003,
    title: 'متدرب - علوم البيانات',
    type: 'internship',
    organization: 'SDAIA',
    description: 'تدريب في مجال علوم البيانات والذكاء الاصطناعي تحت إشراف الهيئة السعودية للبيانات.',
    deadline: '2025-09-01',
    location: 'الرياض، المملكة العربية السعودية',
    latitude: 24.7136,
    longitude: 46.6753,
    xpReward: 80,
    registrationLink: 'https://jadarat.hrsd.gov.sa',
    imageUrl: null,
    isActive: 1,
    createdAt: new Date().toISOString(),
    status: 'open',
    duration: '6 أشهر',
    salary: '5000 ريال/شهر',
  },
];
