export const Colors = {
  primary: {
    purple: '#6B3FA0',
    teal: '#00B8A9',
    purpleLight: '#9B59B6',
    tealLight: '#00D2A0',
  },
  background: {
    app: '#F8F7FF',
    card: '#FFFFFF',
    modal: 'rgba(0,0,0,0.5)',
  },
  text: {
    primary: '#1A1A2E',
    secondary: '#6B7280',
    white: '#FFFFFF',
    muted: '#9CA3AF',
  },
  status: {
    success: '#00C853',
    error: '#EF4444',
    warning: '#F59E0B',
    info: '#3B82F6',
  },
  xp: {
    gold: '#F59E0B',
    goldLight: '#FEF3C7',
    silver: '#9CA3AF',
    bronze: '#D97706',
  },
  gradient: {
    start: '#6B3FA0',
    end: '#00B8A9',
    startLight: '#9B59B6',
    endLight: '#00D2A0',
  },
  opportunity: {
    hackathon: '#6B3FA0',
    hackathonLight: '#EDE9FE',
    internship: '#00B8A9',
    internshipLight: '#E0F7FA',
    opensource: '#00C853',
    opensourceLight: '#DCFCE7',
    volunteer: '#F59E0B',
    volunteerLight: '#FEF3C7',
  },
  ui: {
    border: '#E5E7EB',
    divider: '#F3F4F6',
    disabled: '#D1D5DB',
    placeholder: '#9CA3AF',
    inputBg: '#F9FAFB',
    tabBar: '#FFFFFF',
    shadow: 'rgba(0,0,0,0.08)',
  },
  leaderboard: {
    gold: '#F59E0B',
    goldBg: '#FFFBEB',
    silver: '#9CA3AF',
    silverBg: '#F9FAFB',
    bronze: '#D97706',
    bronzeBg: '#FFF7ED',
  },
};
