export const Strings = {
  app: {
    name: 'عنان لينك',
    tagline: 'وصلتك لكل الفرص التقنية في المملكة العربية السعودية',
  },
  navigation: {
    home: 'الرئيسية',
    opportunities: 'الفرص',
    qrScanner: 'مسح QR',
    leaderboard: 'المتصدرون',
    profile: 'حسابي',
  },
  onboarding: {
    slide1: {
      title: 'اكتشف الفرص التقنية',
      subtitle: 'هاكاثونات، تدريب، مشاريع مفتوحة المصدر، وتطوع — كل الفرص التقنية في مكان واحد لطلاب الحوسبة السعوديين.',
    },
    slide2: {
      title: 'طوّر مهاراتك واكسب XP',
      subtitle: 'شارك في الفعاليات، اجمع نقاط الخبرة، وابنِ مسارك المهني خطوة بخطوة.',
    },
    slide3: {
      title: 'خريطة ذكية ومسح QR',
      subtitle: 'اكتشف الفرص القريبة منك عبر الخريطة، وسجّل حضورك في الفعاليات بلمسة واحدة.',
    },
    next: 'التالي',
    start: 'ابدأ الآن',
    skip: 'تخطي',
  },
  auth: {
    login: {
      title: 'مرحباً بعودتك 👋',
      subtitle: 'سجّل دخولك للوصول لجميع الفرص',
      emailLabel: 'البريد الجامعي',
      emailPlaceholder: 's220001234@kfupm.edu.sa',
      passwordLabel: 'كلمة المرور',
      passwordPlaceholder: 'كلمة المرور',
      forgotPassword: 'نسيت كلمة المرور؟',
      loginButton: 'تسجيل الدخول',
      orDivider: 'أو تسجيل الدخول بـ',
      noAccount: 'ليس لديك حساب؟',
      signUp: 'سجّل الآن',
      github: 'GitHub',
      apple: 'Apple',
      google: 'Google',
    },
    register: {
      title: 'إنشاء حساب',
      step1Title: 'المعلومات الشخصية',
      step2Title: 'كلمة المرور والمهارات',
      step3Title: 'التحقق من البريد',
      firstNameLabel: 'الاسم الأول',
      lastNameLabel: 'اسم العائلة',
      firstNamePlaceholder: 'الاسم الأول',
      lastNamePlaceholder: 'اسم العائلة',
      emailLabel: 'البريد الجامعي',
      emailPlaceholder: 'أدخل بريدك الجامعي',
      universityLabel: 'الجامعة',
      majorLabel: 'التخصص',
      majorPlaceholder: 'علوم الحاسب',
      specialtyLabel: 'المسار التقني',
      passwordLabel: 'كلمة المرور',
      passwordPlaceholder: 'كلمة مرور قوية',
      confirmPasswordLabel: 'تأكيد كلمة المرور',
      confirmPasswordPlaceholder: 'أعد كتابة كلمة المرور',
      academicYearLabel: 'السنة الدراسية',
      skillsLabel: 'اختر مهاراتك التقنية',
      nextButton: 'التالي — الخطوة',
      createButton: 'إنشاء الحساب',
      alreadyHaveAccount: 'لديك حساب؟',
      login: 'سجّل دخولك',
      agreePrefix: 'بالتسجيل أنت توافق على',
      termsLink: 'شروط الاستخدام',
      andWord: 'و',
      privacyLink: 'سياسة الخصوصية',
    },
    otp: {
      title: 'تحقق من بريدك',
      subtitle: 'أرسلنا رمز التحقق إلى',
      resendIn: 'إعادة الإرسال بعد',
      seconds: 'ثانية',
      resendCode: 'أرسل الرمز مجدداً',
      verifyButton: 'تأكيد وإنشاء الحساب',
      changeEmail: 'تغيير البريد الإلكتروني',
      successMessage: 'تم التسجيل! احصل على ٣٠ XP 🎉',
    },
    forgotPassword: {
      title: 'نسيت كلمة المرور؟',
      subtitle: 'أدخل بريدك الجامعي وسنرسل لك رابط الاستعادة',
      emailLabel: 'البريد الجامعي',
      emailPlaceholder: 'أدخل بريدك الجامعي',
      sendButton: 'أرسل رابط الاستعادة',
      backToLogin: 'رجوع لتسجيل الدخول',
      successTitle: 'تم الإرسال!',
      successMessage: 'تحقق من بريدك الجامعي لرابط استعادة كلمة المرور.',
      verifyBySms: 'التحقق عبر SMS',
    },
    errors: {
      emailRequired: 'البريد الجامعي مطلوب',
      emailInvalid: 'أدخل بريداً جامعياً صحيحاً',
      passwordRequired: 'كلمة المرور مطلوبة',
      passwordMin: 'كلمة المرور يجب أن تكون 8 أحرف على الأقل',
      passwordMismatch: 'كلمتا المرور غير متطابقتين',
      firstNameRequired: 'الاسم الأول مطلوب',
      lastNameRequired: 'اسم العائلة مطلوب',
      universityRequired: 'الجامعة مطلوبة',
      majorRequired: 'التخصص مطلوب',
      invalidCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
      genericError: 'حدث خطأ. حاول مجدداً.',
      emailTaken: 'هذا البريد مسجّل مسبقاً',
    },
    universities: [
      'جامعة الملك فهد للبترول والمعادن (KFUPM)',
      'جامعة الملك عبدالعزيز (KAU)',
      'جامعة الملك سعود (KSU)',
      'جامعة الملك عبدالله للعلوم والتقنية (KAUST)',
      'جامعة أم القرى (UQU)',
      'الجامعة الإسلامية (IU)',
      'جامعة الأمير سلطان (PSU)',
      'جامعة الإمام عبدالرحمن بن فيصل (IAU)',
      'جامعة الأمير محمد بن فهد (PMU)',
      'جامعة طيبة',
      'جامعة الطائف',
      'جامعة حائل',
      'جامعة القصيم',
      'جامعة جازان',
      'أخرى',
    ],
    specialties: [
      'Front-end Development',
      'Back-end Development',
      'Mobile Development',
      'Data Science',
      'Artificial Intelligence',
      'Cybersecurity',
      'Cloud Computing',
      'DevOps',
      'UI/UX Design',
      'Full Stack',
      'أخرى',
    ],
    skills: [
      'Frontend',
      'Backend',
      'Mobile',
      'AI/ML',
      'Data Science',
      'Cybersecurity',
      'Cloud',
      'DevOps',
      'UI/UX',
      'Full Stack',
      'Blockchain',
      'IoT',
    ],
    passwordStrength: {
      weak: 'ضعيفة',
      medium: 'متوسطة',
      strong: 'قوية',
    },
  },
  home: {
    greeting: 'مرحباً،',
    level: 'المستوى',
    xpProgress: 'XP للمستوى التالي',
    categories: {
      hackathon: 'هاكاثون',
      internship: 'تدريب',
      opensource: 'مصدر مفتوح',
      volunteer: 'تطوعي',
    },
    recentOpportunities: 'الفرص الأخيرة',
    viewAll: 'عرض الكل',
    viewMap: 'عرض الخريطة',
    stats: {
      applications: 'طلبات',
      hackathons: 'هاكاثون',
      points: 'نقاط',
    },
    available: 'متاح',
    mapTitle: 'الخريطة التفاعلية',
    locationDenied: 'لم يتم منح إذن الموقع — اضغط لفتح الإعدادات',
    mapUnavailable: 'الخريطة غير متاحة',
    mapOpportunitiesInArea: 'فرصة في المنطقة',
  },
  opportunities: {
    filters: {
      all: 'الكل',
      open: 'مفتوح',
      upcoming: 'قادم',
      closed: 'منتهي',
    },
    types: {
      hackathon: 'هاكاثون',
      internship: 'تدريب',
      opensource: 'مصدر مفتوح',
      volunteer: 'تطوعي',
    },
    details: {
      about: 'من المشروع',
      deadline: 'الموعد النهائي',
      location: 'الموقع',
      xpReward: 'مكافأة XP',
      register: 'سجّل الآن',
      apply: 'قدّم الآن',
      viewMore: 'عرض المزيد',
      viewLess: 'عرض أقل',
      requirements: 'المتطلبات',
      participants: 'مشاركون',
      teams: 'فرق',
      prize: 'الجائزة',
      salary: 'الراتب',
      duration: 'المدة',
      spots: 'أماكن متطوعين',
      stars: 'نجوم',
      forks: 'تفرعات',
      language: 'اللغة',
      beginner: 'جيد للمبتدئين',
      topProjects: 'أبرز المشاريع',
    },
    empty: {
      title: 'لا توجد فرص حالياً',
      message: 'تحقق لاحقاً أو تصفح تصنيفات أخرى',
    },
    countdown: {
      days: 'يوم',
      hours: 'ساعة',
      minutes: 'دقيقة',
      ended: 'انتهت المدة',
    },
    bookmark: {
      add: 'حفظ',
      remove: 'إزالة من المحفوظات',
    },
  },
  profile: {
    title: 'حسابي',
    xpLevel: 'المستوى',
    achievements: 'الإنجازات',
    editProfile: 'تعديل الملف الشخصي',
    notifications: 'الإشعارات',
    language: 'اللغة',
    about: 'عن التطبيق',
    logout: 'تسجيل الخروج',
    logoutConfirm: 'هل تريد تسجيل الخروج؟',
    logoutYes: 'نعم',
    logoutNo: 'لا',
    bookmarks: 'المحفوظات',
    skillPaths: 'مسارات التعلم',
  },
  bookmarks: {
    title: 'المحفوظات',
    empty: 'لا توجد فرص محفوظة',
    emptyMessage: 'احفظ الفرص التي تهمك لتجدها هنا بسهولة',
  },
  leaderboard: {
    title: 'المتصدرون',
    weekly: 'أسبوعي',
    monthly: 'شهري',
    alltime: 'الكل',
    rank: 'المركز',
    points: 'نقطة',
    podium: {
      first: 'المركز الأول',
      second: 'المركز الثاني',
      third: 'المركز الثالث',
    },
    myRank: 'مركزك',
    toNextRank: 'نقطة للمركز التالي',
  },
  qr: {
    title: 'مسح QR',
    instruction: 'وجّه الكاميرا نحو رمز QR للفعالية',
    permissionTitle: 'صلاحية الكاميرا',
    permissionMessage: 'نحتاج إذن الكاميرا لمسح رموز QR وتسجيل حضورك في الفعاليات',
    requestPermission: 'منح الإذن',
    permissionDenied: 'تم رفض إذن الكاميرا. افتح الإعدادات لتفعيله.',
    openSettings: 'فتح الإعدادات',
    scanning: 'جاري المسح...',
    success: 'تم المسح بنجاح! 🎉',
    xpEarned: 'حصلت على',
    xpUnit: 'XP',
    done: 'تم!',
    scanAgain: 'مسح آخر',
    howToUse: 'كيفية الاستخدام',
    steps: [
      'احضر إلى موقع الفعالية',
      'ابحث عن رمز QR الخاص بالفعالية',
      'وجّه الكاميرا نحو الرمز',
      'سيتم تسجيل حضورك تلقائياً',
    ],
  },
  skillPath: {
    title: 'مسارات التعلم',
    tracks: {
      ai: 'الذكاء الاصطناعي',
      mobile: 'تطوير التطبيقات',
      backend: 'تطوير الخوادم',
      frontend: 'تطوير الواجهات',
      security: 'الأمن السيبراني',
      cloud: 'الحوسبة السحابية',
    },
    progress: 'وحدة',
    difficulty: {
      beginner: 'مبتدئ',
      intermediate: 'متوسط',
      advanced: 'متقدم',
    },
    units: 'وحدات القسم',
    completed: 'مكتمل',
    start: 'ابدأ',
    continue: 'تابع',
  },
  errors: {
    generic: 'حدث خطأ غير متوقع',
    network: 'تحقق من اتصالك بالإنترنت',
    notFound: 'لم يتم العثور على المحتوى',
    loading: 'فشل تحميل البيانات. حاول مجدداً.',
  },
};
